[package]
name = "telegraf"
version = "0.1.0"
authors = ["Max Mindlin <maxmindlin@gmail.com>"]
edition = "2018"
repository = "https://github.com/maxmindlin/telegraf-rust"
description = "Minimal rust wrapper for the telegraf/influxdb protocol"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.1.1"